### PR TITLE
Boaz stars info

### PR DESCRIPTION
**Pull request by boazpoolman**

### CODE REVIEW

**Comment by malgamves** [comment]
heyy thanks for the PR, added a new colomn.. could you fill that in and I'll merge after. Sorry for the abrupt change!

**Comment by boazpoolman** [comment]
Updated!

**Comment by malgamves** [comment]
hey @boazpoolman that last section really should be "ways I like to contribute to Strapi" that was my intention with that. Trying to get a good idea of what folks like. One last change 🤞 😬

**Comment by boazpoolman** [comment]
Haha allright, updated it!

**Comment by malgamves** [comment]
awesome!! Thank you 🚀 welcome ⭐

**Pull request merged**
