### PR TITLE
Monico stars info

### PR DESCRIPTION
**Pull request by monico-moreno**

### CODE REVIEW

**Comment by malgamves** [comment]
heyy thanks for the PR, added a new column.. could you fill that in and I'll merge after. Sorry for the abrupt change!

**Comment by monico-moreno** [comment]
Hey, @malgamves , new column added. 👍

**Comment by malgamves** [comment]
Heyy @monico-moreno that last section really should be "ways I like to contribute to Strapi" that was my intention with that. Trying to get a good idea of what folks like. One last change 🤞 😬

**Comment by monico-moreno** [comment]
Ha!  🤣  I am too preoccupied with having fun with this!  Sorry about that!  Will fix.

**Comment by monico-moreno** [comment]
There we go!

**Comment by monico-moreno** [comment]
Looks like I need to get Boaz's changes....will do in a moment...in a mtg at work...

**Comment by monico-moreno** [comment]
@malgamves  Pulled latest from upstream (Boaz's changes), rebased, resolved conflicts, and up to date with latest! 👍

**Comment by malgamves** [comment]
looks great!! Thanks, good to have you on the program, welcome ⭐

**Pull request merged**
