### PR TITLE
[add] Saad Stars Info

### PR DESCRIPTION
**Pull request by Saad-ISAA**

### CODE REVIEW

**Comment by malgamves** [comment]
hey @Saad-ISAA the last section was left to give people an idea of how you would like to contribute to the Strapi community. I think some of the items in the column aren't relevant. Could you change that?

**Comment by Saad-ISAA** [comment]
> hey @Saad-ISAA the last section was left to give people an idea of how you would like to contribute to the Strapi community. I think some of the items in the column aren't relevant. Could you change that?

sure. changing

**Comment by Saad-ISAA** [comment]
done

**Comment by malgamves** [comment]
hey, looks like there's a couple merge conflicts 😅

**Comment by Saad-ISAA** [comment]
aaah... there was a push before i comitted my update

**Comment by Saad-ISAA** [comment]
@malgamves  it's resolved for merge

**Pull request merged**
